source 'https://github.com/xiaochuanxu/FFSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'FFSpecialKit_Example' do
  pod 'FFSpecialKit', :path => '../'

  target 'FFSpecialKit_Tests' do
    inherit! :search_paths

    
  end
end
